ASP_Core_EF/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASP_Core_EF.Services;
using ASP_Core_EF.Models;
using System.Net;

namespace ASP_Core_EF.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourse _Course;

        public CourseController(ICourse _ICourse)
        {
            _Course = _ICourse;
        }
        public IActionResult Index()
        {
            return View(_Course.GetCourses);
        }
        [HttpGet]
        public IActionResult Create()
        {
            Course model=new Course();
            model.CourseId = 0;

            return View(model);
        }
        [HttpPost]
        public IActionResult Create(Course model)
        {
            if (ModelState.IsValid)
            {

                _Course.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                //Error 
                return NotFound();
            }
            
            else
            {
                Course model = _Course.GetCourse(Id);
                return View(model);
            }
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirm(int? Id)
        {
            _Course.Remove(Id);
            return RedirectToAction("Index");
           
        }

        [HttpGet]
        public IActionResult Details(int? Id)
        {

            return View(_Course.GetCourse(Id));
        }

        [HttpGet]
        public IActionResult Edit(int? Id)
         {
            var model = _Course.GetCourse(Id);
            return View("Create",model);
        }



    }
}

ASP_Core_EF/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASP_Core_EF.Services;
using ASP_Core_EF.Models;

namespace ASP_Core_EF.Controllers
{
    public class EnrollmentController : Controller
    {
        private readonly IEnrollment _Enrollment;
        private readonly ICourse _Cousre;
        private readonly IStudent _Student;

        public EnrollmentController(IEnrollment _IEnrollment,ICourse _ICousre, IStudent _IStudent)
        {
            _Enrollment = _IEnrollment;
            _Cousre = _ICousre;
            _Student = _IStudent;
        }
        public IActionResult Index()
        {
            return View(_Enrollment.GetEnrollments);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Course = _Cousre.GetCourses;
            ViewBag.Student = _Student.GetStudents;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Enrollment model)
        {
            if (ModelState.IsValid)
            {
                _Enrollment.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            Enrollment model = _Enrollment.GetEnrollment(Id);
            return View(model);
        }

        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirm(int? Id)
        {
            _Enrollment.Remove(Id);
            return RedirectToAction("Index");
        }

       
    }
}

ASP_Core_EF/Controllers/GenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASP_Core_EF.Services;
using ASP_Core_EF.Models;

namespace ASP_Core_EF.Controllers
{
    public class GenderController : Controller
    {
        private readonly IGender _Gender;
        public GenderController(IGender _IGender)
        {
            _Gender = _IGender;
        }
        public IActionResult Index()
        {
            return View(_Gender.GetGenders);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Gender model)
        {
            if (ModelState.IsValid)
            {
                _Gender.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                //Error 
                return NotFound();
            }

            else
            {
                Gender model = _Gender.GetGender(Id);
                return View(model);
            }
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int? Id)
        {
            _Gender.Remove(Id);
            return RedirectToAction("Index");

        }

    }
}

ASP_Core_EF/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASP_Core_EF.Services;
using ASP_Core_EF.Models;

namespace ASP_Core_EF.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudent _Student;
        private readonly IGender _Gender;

        public StudentController(IStudent _IStudent,IGender _IGender)
        {
            _Student = _IStudent;
            _Gender = _IGender;
        }
        public IActionResult Index()
        {
            return View(_Student.GetStudents);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Genders = _Gender.GetGenders;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Student model)
        {
            if (ModelState.IsValid)
            {
                _Student.Add(model);
              return  RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            Student model = _Student.GetStudent(Id);
            return View(model);
        }

        [HttpPost,ActionName("Delete")]
        public  IActionResult DeleteConfirm(int ? Id)
        {
            _Student.Remove(Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int? Id)
        {
            return View(_Student.GetStudent(Id));
        }

    }
}

ASP_Core_EF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_Core_EF</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ASP_Core_EF</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Enrollment" asp-action="Index">Enrollments</a></li>
                    <li><a asp-area="" asp-controller="Student" asp-action="Index">Students</a></li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Control Panel <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a  asp-area="" asp-controller="Gender" asp-action="Index">Genders</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a asp-area="" asp-controller="Course" asp-action="Index">Course</a></li>
                            
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ASP_Core_EF</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>